export enum QUERYKEYS {
  FETCHPROFILE = 'FETCHPROFILE',
  FETCHPROFILEPICTURE = 'FETCHPROFILEPICTURE',
  FETCHROLES = 'FETCHROLES',
  FETCHROLE = 'FETCHROLE',
  FETCHPERMISSIONS = 'FETCHPERMISSIONS',
  FETCHUSERS = 'FETCHUSERS',
  FETCHAPPUSERS = 'FETCHAPPUSERS',
  FETCHSYSTEMUSERS = 'FETCHSYSTEMUSERS',
  FETCHEBOOKS = 'FETCHEBOOKS',
  FETCHEBOOKURL = 'FETCHEBOOKURL',
  FETCHFACILITIES = 'FETCHFACILITIES',
}
